name: automated test

on:
  workflow_dispatch:
  push:
    branches: [feature/github-action-test]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.14"]

    steps:
      - uses: actions/checkout@v5
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: install pipenv
        run: python -m pip install --upgrade pip pipenv

      - name: install dependencies
        run: pipenv sync --dev

      - name: build package
        run: pipenv run python -m build

      - name: testing
        run: pipenv run pytest
